version: "3"

services:
  queue:
    image: rabbitmq:3.7.7-management-alpine
    restart: always
    ports:
      - 5673:5672
      - 15673:15672
    volumes:
    - rabbitmq-data:/var/lib/rabbitmq
    environment:
      RABBITMQ_VM_MEMORY_HIGH_WATERMARK: 2000MiB
      RABBITMQ_ERLANG_COOKIE: f6fAjy5yes
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
  mysql:
    image: mysql:8.0.21
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foreman
      MYSQL_USER: foreman
      MYSQL_PASSWORD: foreman
    ports:
      - 3307:3306

#  postgres:
#    build:
#      context: ./.docker/postgres
#    restart: always
#    volumes:
#      - ./.docker/postgres/conf/postgresql.conf:/etc/postgresql.conf
#      - ./.docker/postgres/data/customers.sql:/docker-entrypoint-initdb.d/init.sql
#    environment:
#      POSTGRES_PASSWORD: 123456789
#      POSTGRES_USER: brigadier
#      DB_NAME: brigadier
#
#    ports:
#      - 5432:5432
#    command: postgres -c config_file=/etc/postgresql.conf

volumes:
  db-data: ~
  rabbitmq-data: ~
